# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: event_booking_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}

  event-service:
    build: ./event-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  booking-service:
    build: ./booking-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - event-service

  notification-service:
    build: ./notification-service
    ports:
      - "8003:8003"

  frontend:
    build: ./frontend-service
    ports:
      - "5173:80"
    depends_on:
      - user-service
      - event-service

volumes:
  pgdata: